# Generated by Django 5.2.17 on 2026-09-27 05:02

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="MemoryItem",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("text", models.TextField()),
                (
                    "kind",
                    models.CharField(
                        choices=[("fact", "Student fact"), ("inference", "AI inference")], default="fact", max_length=20
                    ),
                ),
                ("owner", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="Profile",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("institution", models.CharField(blank=True, max_length=200)),
                ("program", models.CharField(blank=True, max_length=200)),
                ("department", models.CharField(blank=True, max_length=200)),
                ("academic_year", models.CharField(blank=True, max_length=30)),
                ("semester", models.CharField(blank=True, max_length=30)),
                ("goals", models.TextField(blank=True)),
                ("language", models.CharField(default="English", max_length=50)),
                ("timezone", models.CharField(default="UTC", max_length=80)),
                ("memory_enabled", models.BooleanField(default=False)),
                ("reminders_enabled", models.BooleanField(default=True)),
                ("daily_limit", models.PositiveIntegerField(default=120)),
                ("session_minutes", models.PositiveIntegerField(default=30)),
                ("break_minutes", models.PositiveIntegerField(default=10)),
                ("availability", models.JSONField(default=list)),
                (
                    "user",
                    models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
                ),
            ],
        ),
    ]
