# Generated by Django 5.2.17 on 2026-09-27 05:02

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("courses", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Plan",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("status", models.CharField(default="draft", max_length=20)),
                ("reason", models.TextField(default="Initial plan")),
                ("unscheduled", models.JSONField(default=list)),
                ("conflicts", models.JSONField(default=list)),
                ("owner", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                (
                    "previous",
                    models.ForeignKey(
                        blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to="planning.plan"
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="PlannedSession",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("starts_at", models.DateTimeField()),
                ("ends_at", models.DateTimeField()),
                ("kind", models.CharField(default="learn", max_length=20)),
                ("status", models.CharField(default="pending", max_length=20)),
                ("locked", models.BooleanField(default=False)),
                ("actual_minutes", models.PositiveIntegerField(default=0)),
                ("owner", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                (
                    "plan",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, related_name="sessions", to="planning.plan"
                    ),
                ),
                ("topic", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to="courses.topic")),
            ],
            options={
                "abstract": False,
            },
        ),
    ]
