# Generated by Django 5.2.17 on 2026-09-29 04:52

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("courses", "0001_initial"),
        ("exams", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="exam",
            name="all_topics",
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name="exam",
            name="topics",
            field=models.ManyToManyField(blank=True, to="courses.topic"),
        ),
    ]
