# Generated by Django 5.2.17 on 2026-09-27 05:02

import django.db.models.deletion
import documents.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("courses", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Document",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("title", models.CharField(max_length=200)),
                (
                    "kind",
                    models.CharField(
                        choices=[("material", "Material"), ("syllabus", "Syllabus"), ("timetable", "Timetable")],
                        default="material",
                        max_length=20,
                    ),
                ),
                ("file", models.FileField(upload_to=documents.models.private_path)),
                ("status", models.CharField(default="uploaded", max_length=20)),
                ("error", models.TextField(blank=True)),
                ("confirmed", models.BooleanField(default=False)),
                ("generation", models.PositiveIntegerField(default=0)),
                (
                    "course",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, related_name="documents", to="courses.course"
                    ),
                ),
                ("owner", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="DocumentPage",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("number", models.PositiveIntegerField()),
                ("text", models.TextField(blank=True)),
                ("confidence", models.FloatField(default=1)),
                ("warning", models.TextField(blank=True)),
                (
                    "document",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, related_name="pages", to="documents.document"
                    ),
                ),
            ],
            options={
                "ordering": ["number"],
            },
        ),
        migrations.CreateModel(
            name="TopicMapping",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("score", models.FloatField()),
                ("reason", models.TextField()),
                ("confirmed", models.BooleanField(default=False)),
                ("owner", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ("page", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to="documents.documentpage")),
                ("topic", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to="courses.topic")),
            ],
        ),
        migrations.AddConstraint(
            model_name="documentpage",
            constraint=models.UniqueConstraint(fields=("document", "number"), name="unique_document_page"),
        ),
        migrations.AddConstraint(
            model_name="topicmapping",
            constraint=models.UniqueConstraint(fields=("topic", "page"), name="unique_topic_page"),
        ),
    ]
