# Generated by Django 5.2.17 on 2026-09-27 05:02

import django.db.models.deletion
import exports.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("planning", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="ExportJob",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "kind",
                    models.CharField(
                        choices=[("data", "All data"), ("pdf", "Plan PDF"), ("ics", "Calendar")], max_length=10
                    ),
                ),
                ("status", models.CharField(default="queued", max_length=20)),
                ("error", models.TextField(blank=True)),
                ("file", models.FileField(blank=True, upload_to=exports.models.export_path)),
                ("owner", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                (
                    "plan",
                    models.ForeignKey(
                        blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to="planning.plan"
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
    ]
