# Generated by Django 5.2.17 on 2026-09-27 05:02

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("courses", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Quiz",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("title", models.CharField(default="Practice quiz", max_length=200)),
                ("difficulty", models.CharField(default="medium", max_length=20)),
                ("length", models.PositiveSmallIntegerField(default=5)),
                ("status", models.CharField(default="queued", max_length=20)),
                ("error", models.TextField(blank=True)),
                ("questions", models.JSONField(default=list)),
                ("course", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to="courses.course")),
                ("owner", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                (
                    "topic",
                    models.ForeignKey(
                        blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to="courses.topic"
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="Attempt",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("answers", models.JSONField()),
                ("correct", models.PositiveIntegerField()),
                ("total", models.PositiveIntegerField()),
                ("results", models.JSONField()),
                ("owner", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ("quiz", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to="quizzes.quiz")),
            ],
            options={
                "constraints": [models.UniqueConstraint(fields=("owner", "quiz"), name="one_scored_attempt_per_quiz")],
            },
        ),
    ]
