# Generated by Django 5.2.17 on 2026-09-27 05:02

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("courses", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="ChatSession",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "mode",
                    models.CharField(
                        choices=[
                            ("material", "Ask My Material"),
                            ("tutor", "Tutor Me"),
                            ("guidance", "Study and Career Guidance"),
                        ],
                        default="material",
                        max_length=20,
                    ),
                ),
                ("title", models.CharField(default="New conversation", max_length=200)),
                ("course", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to="courses.course")),
                ("owner", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="ChatMessage",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("role", models.CharField(max_length=20)),
                ("text", models.TextField()),
                ("citations", models.JSONField(default=list)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "session",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, related_name="messages", to="tutoring.chatsession"
                    ),
                ),
            ],
        ),
    ]
